=== BraisPN/LM/xml/exer25/items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="item" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="photo"/>
                            <xs:element name="tags" type="xs:string"/>
                            <xs:element name="diameter" type="xs:double"/>
                            <xs:element name="weigth" type="xs:double"/>
                            <xs:element name="price" type="priceType"/>
                            <xs:element name="size" type="sizeType" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
        <xs:minExclusive value="0"></xs:minExclusive>
        <xs:pattern value=".*\.\d{2}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
        <xs:simpleType name="sizeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Big"></xs:enumeration>
            <xs:enumeration value="Small"></xs:enumeration>
            <xs:enumeration value=""></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== BraisPN/LM/xml/exer25/items.xml
<items xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="items.xsd">
    <item>
        <name>Pepo</name>
        <photo></photo>
        <tags></tags>
        <diameter>20</diameter>
        <weigth>20</weigth>
        <price>10.00</price>
        <size></size>
    </item>
</items>
